name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Node.js and Install dependencies for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for Frontend
        run: |
          cd FrontEnd/frontend
          npm install

      - name: Build Frontend
        run: |
          cd FrontEnd/frontend
          npm run build

      
